### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by stratisioannidis** [neu-spiral/SPIRAL-Handbook#2]
@alican This link was broken:

  - Complete the [Safety Training](https://ehsa.nunet.neu.edu/ehstrn/EHStrainwebisapi.dll/EXEC) (if needed, supervisor: Stephen Keane). 

I am removing it, as it was the first link on the "Getting Started" guide. It is a bad omen when you are getting started, and the very first link is broken :( Not sure what it is anyway

**Comment by alicanb** [comment]
I'm not sure why that happens, but if you click restart link, then the correct page opens (the addresss doesn't change though).

**Comment by alicanb** [comment]
Nvm, I think I got it, I'm adding it back.
