### ISSUE TITLE
Should we move training to lab specific pages?

### ISSUE THREAD

**Issue by alicanb** [neu-spiral/SPIRAL-Handbook#3]
@stratisioannidis  Should we move this section to CSL? I don't think everybody needs to complete this? 

## Training 

Confirm with your advisor which of the following training courses you need to complete.

### Human Subject Protection and Research Integrity Training
 
Complete [this training class](http://phrp.nihtraining.com/users/login.php) (~3 hours) and send certificate pdf to your advisor.

**Comment by stratisioannidis** [comment]
I would keep it. Most of us need this.

-- 
Assistant Professor
Electrical and Computer Engineering
Northeastern University
ioannidis@ece.neu.edu
http://ece.neu.edu/fac-ece/ioannidis
